# coding: utf-8

"""
    Fabric Orchestrator API

    This is Fabric Orchestrator API  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: kthare10@unc.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PoaData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'str',
        'request_id': 'str',
        'info': 'PoaDataInfo'
    }

    attribute_map = {
        'operation': 'operation',
        'request_id': 'request_id',
        'info': 'info'
    }

    def __init__(self, operation=None, request_id=None, info=None):  # noqa: E501
        """PoaData - a model defined in Swagger"""  # noqa: E501
        self._operation = None
        self._request_id = None
        self._info = None
        self.discriminator = None
        if operation is not None:
            self.operation = operation
        if request_id is not None:
            self.request_id = request_id
        if info is not None:
            self.info = info

    @property
    def operation(self):
        """Gets the operation of this PoaData.  # noqa: E501


        :return: The operation of this PoaData.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this PoaData.


        :param operation: The operation of this PoaData.  # noqa: E501
        :type: str
        """

        self._operation = operation

    @property
    def request_id(self):
        """Gets the request_id of this PoaData.  # noqa: E501


        :return: The request_id of this PoaData.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this PoaData.


        :param request_id: The request_id of this PoaData.  # noqa: E501
        :type: str
        """

        self._request_id = request_id

    @property
    def info(self):
        """Gets the info of this PoaData.  # noqa: E501


        :return: The info of this PoaData.  # noqa: E501
        :rtype: PoaDataInfo
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this PoaData.


        :param info: The info of this PoaData.  # noqa: E501
        :type: PoaDataInfo
        """

        self._info = info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoaData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoaData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
